server:
  port: 8082
spring:
  datasource:
    #数据源基本配置
    username: buffet
    password: abc123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.229.32.226:3306/buffet?serverTimezone=Asia/Shanghai&useUnicode=true&amp&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

    #redis配置
  cache:
    type: redis
  redis:
    host: 121.199.49.199
    password: 123456
    port: 6379
#打印日志
logging:
  level:
    cn.ffcs.buffet: info
  file:
    name: log\buffet.log

#mybatis-pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

#mybatis配置
mybatis:
  #mybatis配置文件
  config-location: classpath:mybatis/mybatis.xml
  #mybatis的mapper位置
  mapper-locations: classpath:mybatis/mapper/*.xml
